---
title: "stroke"
author: "Subeen Leem"
output: html_document
date: "2024-04-07"
---

패키지/데이터 불러오기
```{r message=FALSE}
library(tableone)
library(survey)
library(ggplot2)
library(MatchIt)

setwd('C:\\subeen\\shim\\pps')
data <- read.csv("stroke 39965 240405.csv")
data <- na.omit(data)
```

### 변수 지정
```{r}
vars <- c("age","male","smok","BMI","TOAST","hx_tia","chd","hx_htn","hx_dm","hx_hl","hx_af","atx_plt","atx_coa","Rehab","dtx_plt","dtx_coa","dtx_statin","Stroke_edu","Recur_1yr","Recur_1yr.yesno")

fvars <- c("tx_throm","male","smok","TOAST","hx_tia","chd","hx_htn","hx_dm","hx_hl","hx_af","atx_plt","atx_coa","Rehab","dtx_plt","dtx_coa","dtx_statin","Stroke_edu", "Recur_1yr.yesno")
```

### 0. Raw Table
```{r}
tableone <- CreateTableOne(strata = "tx_throm", 
                               vars = vars,
                               factorVars = fvars,
                               data = data)

#t0/t1에 맞추어 y0/y1의 빈도수 확인
#summary(tableone)
  
#Crude 상태에서의 개별 통계량과 집단에 따른 유의차, SMD 확인
print(tableone, smd=T)
```

# 1. PSW 분석
### 1-0. pscore, sw 변수 생성
```{r}
reg <- glm(tx_throm ~ age+male+smok+BMI+TOAST+hx_tia+chd+hx_htn+hx_dm+hx_hl+hx_af+atx_plt+atx_coa+Rehab+dtx_plt+dtx_coa+dtx_statin+Stroke_edu, 
          family=binomial(), 
          data=data) 
#summary(reg)

data$pscore <- c(predict.glm(reg, type="response")) #종속변수가 될 확률

#data$ipw <- ifelse(data$tx_throm==1, 1/data$pscore, 1/(1-data$pscore))

prop <- sum(data$tx_throm)/length(data$tx_throm)
data$sw <- ifelse(data$tx_throm==1, prop/data$pscore, (1-prop)/(1-data$pscore))

head(data)
```

### 1-1. After PSW
```{r}
svydes.sw <-svydesign(id = ~id, 
                      weights = ~sw, 
                      strata = ~tx_throm,
                      data = data)
svy.sw.tableone <- svyCreateTableOne(strata="tx_throm",
                                     vars = vars,
                                     factorVars = fvars, 
                                     data = svydes.sw)
print(svy.sw.tableone, smd=T)
```

### 1-2. 시각화
```{r, fig.height=10}
#weighting 이전의 subset by tx_throm
tx_throm.1 <- dplyr::filter(data, tx_throm== 1)
tx_throm.0 <- dplyr::filter(data, tx_throm== 0)

#SW svyset의 subset by tx_throm
svydes.sw.tx_throm.1<-subset(svydes.sw,tx_throm== 1)
svydes.sw.tx_throm.0<-subset(svydes.sw,tx_throm== 0)

split.screen(c(2,2))

screen(1);boxplot(tx_throm.1$pscore, main="tx_throm.1 before PSW",xlab = "propensity score")
screen(2);boxplot(tx_throm.0$pscore, main="tx_throm.0 before PSW",xlab = "propensity score")
screen(3);svyboxplot(pscore~1, ylim = c(0, 1), svydes.sw.tx_throm.1,all.outliers=TRUE,main="tx_throm.1 after PSW",xlab = "propensity score")
screen(4);svyboxplot(pscore~1, ylim = c(0, 1), svydes.sw.tx_throm.0,all.outliers=TRUE,main="tx_throm.0 after PSW",xlab = "propensity score")
```

### 1-3. Before & After PSW pscore
```{r}
pscore.beforePSW <- CreateTableOne(strata = "tx_throm", vars = "pscore", data = data, test = T)
print(pscore.beforePSW, smd=T)

pscore.afterPSW <- svyCreateTableOne(strata="tx_throm", vars = "pscore", data = svydes.sw)
print(pscore.afterPSW, smd=T)
```

# 2. PSM 분석
### 2-1. 시각화
```
pscore sd의 0.25 즉, sd(data$pscore) = 0.1104054 이니까 sd(data$pscore)*0.25 = 0.02760135. 
caliper를 줄이면 더 정밀한 매칭이 되지만 샘플은 줄어든다. 
```
```{r warning = FALSE, message = FALSE}
psmlist <- matchit(tx_throm ~ age+male+smok+BMI+TOAST+hx_tia+chd+hx_htn+hx_dm+hx_hl+hx_af+atx_plt+atx_coa+Rehab+dtx_plt+dtx_coa+dtx_statin+Stroke_edu,
                                        data = data,
                                        distance = "glm",
                                        method = "nearest",
                                        replace=FALSE,
                                        estimand = "ATT",
                                        caliper = 0.02760135,
                                        ratio = 1)

#plot(psmlist) #QQ plot
plot(psmlist, type = "jitter")
plot(psmlist, type = "hist", breaks=10)
```

### 2-2. After PSM
data.psm은 기존의 변수에 distance, weight, subclass라는 세 개의 변수가 더 추가됨.
- distance: 각 propensity score의 차이에 의한 거리(pscore와 동일)
- weight: weight option을 사용했을 때 사용된 값(이 자료는 weight option을 사용하지 않음)
- subclass: 짝짓기가 이루어진 자료들의 번호
method='optimal'일경우 생성되며 'nearest'에서는 생성안됨.
```{r}
data.psm <- match.data(psmlist)
#head(data.psm)

psm.tableone <- CreateTableOne(strata = "tx_throm", 
                               vars = vars,
                               factorVars = fvars,
                               data = data.psm)

print(psm.tableone, smd=T)
```
